[package]
name = "nixflow"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
camino = "1.1.9"
clap = { version = "4.5.37", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
thiserror = "2.0.12"
